# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'

variables:
  imageName: 'easypedconfweb'
  dockerid: 'easymedicine.azurecr.io'
  appname: 'easypedconfweb'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
- script: |
    echo 'HOST=0.0.0.0' > .env
    echo 'PORT=3000' >> .env
    echo 'API_URL=$(API_URL)' >> .env
- script: |
    npm install
    docker build -f Dockerfile -t $(dockerId)/$(imageName) .
    docker login $(dockerId) -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
    docker push $(dockerId)/$(imageName)
  displayName: 'docker build'
