version: '3.2'
services:
  web:
    image: easymedicine.azurecr.io/easypedconfweb:97
    restart: always
    depends_on:
      - api
    ports:
      - "3000:3000"
    environment:
      API_URL: 'http://easypedconf.azurewebsites.net/api/v1'
  api:
    image: easymedicine.azurecr.io/easypedconfapi:95
    restart: always
    ports:
      - "3333:3333"
  nginx:
    image: easymedicine.azurecr.io/nginx:latest
    restart: always
    depends_on:
      - web
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro